version: "3.7"

services:
  couchbase:
    container_name: couchbase
    image: couchbase:latest
    ports:
      - "8091-8096:8091-8096" # UI ports
      - "11210-11211:11210-11211" # Engine ports
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: ${DB_USERNAME}
      COUCHBASE_ADMINISTRATOR_PASSWORD: ${DB_PASSWORD}
    volumes:
      - couchbase_data:/opt/couchbase/var
      - couchbase_config:/opt/couchbase/etc

  express-app:
    container_name: express-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - couchbase

volumes:
  couchbase_data:
  couchbase_config: